### ISSUE TITLE
Make status"es" into  hyperlinks pointing to files for that dandiset

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets-healthstatus#12]
E.g. in the line

000362 | 52 passed, 0 failed, 0 timed out | 0 passed, 2 failed, 50 timed out

the last column would be (besides references relative, not absolute URLs like here):

000362 | 52 passed, 0 failed, 0 timed out | [0 passed](https://github.com/dandi/dandisets-healthstatus/blob/main/000362/status.yaml#L64), [2 failed](https://github.com/dandi/dandisets-healthstatus/blob/main/000362/status.yaml#L61), [50 timed out](https://github.com/dandi/dandisets-healthstatus/blob/main/000362/status.yaml#L65)

I do realize that getting to corresponding line numer might be tricky but solutions in https://github.com/yaml/pyyaml/issues/456  suggest it might be possible?

if not possible in some sensible fashion, at least make it urls to that status.yaml so it is still reasonably easy to get to those files.

**Comment by jwodder** [comment]
@yarikoptic I don't think linking to individual lines is reasonably feasible.  Thus, we'd instead be linking both columns (I'm assuming you're just focusing on the last column here for illustration purposes and that you want the second column to be a link as well) to `{dandiset_id}/status.yaml`, at which point it seems more reasonable to solely link the Dandiset ID in the first column to the `status.yaml` file, i.e:

> [000362](https://github.com/dandi/dandisets-healthstatus/blob/main/000362/status.yaml) | 52 passed, 0 failed, 0 timed out | 0 passed, 2 failed, 50 timed out

Is that acceptable?

**Comment by yarikoptic** [comment]
ok.
