### ISSUE TITLE
total number in the header should not be just a sum

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets-healthstatus#15]
ATM it has `Passed (295/34452) | Failed (103/17930) | Timed Out (66/2626)` in which each number is just a sum across two tests (pynwb_open_load_ns and matnwb_nwbRead) rows.  It is not interesting to see in the header just the sum -- we would want to see for "Passed" to be a `len(intersection(succeeded))` and for "Failed" or "Timed out" `len(union(failed))` items (dandisets or individual files), so we could see how many good (pass all tests - could be opened with **any** of the tool) dandisets/files  we have, and how many dandisets/files have issue (would fail with **some** tool).

**Comment by jwodder** [comment]
@yarikoptic To be clear, you want the summary table's header to show the numbers of assets that pass all tests, fail any tests, and timed out on any tests, correct?  Should Dandiset quantities still be shown, and, if so, what should those values be?

**Comment by yarikoptic** [comment]
> @yarikoptic To be clear, you want the summary table's header to show the numbers of assets that pass all tests, fail any tests, and time out on any tests, correct?

correct

>  Should Dandiset quantities still be shown, and, if so, what should those values be?

yes, they should be shown. And they should correspond to  the numbers of dandisets where all assets pass all tests, dandisets which have any asset which fail any tests, and dandisets which have any asset which time out on any tests
