### ISSUE TITLE
Add references/URLs to specific lines in the status.yaml files

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets-healthstatus#22]
As requested in https://github.com/dandi/dandisets-healthstatus/issues/18#issuecomment-1382055138 with some pointers to possible solutions presented on SO. Might be easier to implement after/along with #21 so when (re)loading results from .yaml files just keep track about location of each entry there.

**Comment by jwodder** [comment]
@yarikoptic Exactly which lines in `status.yaml` files should the README link to?  (Use [this file](https://github.com/dandi/dandisets-healthstatus/blob/8981bd6b8c10503edcb99d1d44471714e4d946f9/code/test/data/report-input/000001/status.yaml) as an example if necessary.)  Your comment [here](https://github.com/dandi/dandisets-healthstatus/issues/18#issuecomment-1384531609) implies that you want the "X passed", "Y failed", and "Z timed out" strings under each test to each link to the matching `assets_*` fields in the matching test item, but [the referenced SO link](https://stackoverflow.com/q/13319067/744178) only supports adding the line number for the start of a mapping to that mapping, not assigning line numbers to string fields in mappings.

**Comment by yarikoptic** [comment]
[3 passed](https://github.com/dandi/dandisets-healthstatus/blob/8981bd6b8c10503edcb99d1d44471714e4d946f9/code/test/data/report-input/000001/status.yaml#L6) , 0 failed, 0 timeout

so -- yes - to the matching `assets_` fields.  If that top level SO doesn't give a complete solution, please have a look below e.g. at https://stackoverflow.com/a/70679131/1265472 or mentioned solution there using ruaml.yaml.
