### ISSUE TITLE
add command to run individual test on given file(s)

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets-healthstatus#38]
Now that we have `click` CLI , it probably should be relatively easy to add a command like

```
test-files -t testname [files]
```
where `testname` would be one of the available ATM `pynwb_open_load_ns` or `matnwb_nwbRead`.  It would just run, dump output to screen ,and exit with non-0 if testing any file fails, nothing stored in status etc.   May be it could only report corresponding versions of the matnwb etc?

**Comment by jwodder** [comment]
@yarikoptic By "dump output to screen", do you mean that you want to see the output only if the test fails or also if it passes or times out?  Doing the latter would complicate the code.

**Comment by yarikoptic** [comment]
Go easy route - fine to see when ok as well.
