### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets-healthstatus#4]
In the spirit of https://github.com/dandi/dandi-api-webshots and https://github.com/datalad/datalad-usage-dashboard we should have a dashboard which would have 

- summary on top which for each test (row) would list
  - `# ok` - number of dandisets/number of files in which it is all ok
  -  `# fail` - dandisets/number of files hyperlinks leading to the `status.yaml` files so we could see details

I do not think we would need lengthy alternative "transpose" with row per dandiset but may be we will.

**Comment by jwodder** [comment]
@yarikoptic There is a README, generated according to the spec in #1.  I simply failed to commit it at first.

**Comment by jwodder** [comment]
@yarikoptic Could you show an example of what exactly you want the top summary to look like?

**Comment by yarikoptic** [comment]
some like

| Test / (dandisets/files) | ok (80/10000) | fail (20/2000) |
| --- | --- | --- |
| pynwb_open_load_ns | 100/12000 | - |
| matnwb_open_load | 80 / 10000 | 20/2000: [000349](https://github.com/dandi/dandisets-healthstatus/blob/main/000349/status.yaml)/10 [000350](https://github.com/dandi/dandisets-healthstatus/blob/main/000350/status.yaml)/4 ... |
