### ISSUE TITLE
Add summary over versions of libraries

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets-healthstatus#62]
Inspired by my inability to react to @rly 's comment during nwb/dandi meeting that a new matnwb was released fixing some issues.  I think that while composing our detailed per dandiset table we should prepend it with summary over versions of libraries. E.g.

```markdown
 ## Versions (good/bad/not-tested):

-  hdmf: 3.11.0 (900/100/10000), 3.10.0 (100/800/10100), ...
-  matnwb: v2.6.0.2 (0/10000/100), ...
-  pynwb: 2.5.0 (11000/0/0)
```

that would give us a nice quick idea on how much testing was done for the recent versions. 

bonus feature: those numbers could be hyperlinks to a sample file which passed/failed (not so interesting for not-tested I guess) for the corresponding version.

**Comment by jwodder** [comment]
@yarikoptic What exactly is the "not tested" number supposed to be?  If an asset wasn't tested, then it won't have any associated package versions, as those are only used during testing.

**Comment by yarikoptic** [comment]
"not tested" as "not tested with that version", i.e. it would include assets not tested with any version yet or tested only with other versions.

**Comment by jwodder** [comment]
@yarikoptic Does "bad" include "timed out", or should that category just be ignored?

**Comment by yarikoptic** [comment]
oh, forgot about those! Let's then make it `good/bad/timed-out/not-tested` for consistency/to be complete.
