### ISSUE TITLE
MatNWB installation steps still needed?

### ISSUE THREAD

**Issue by jwodder** [dandi/dandisets-healthstatus#65]
@yarikoptic In commit 035e64ee, you removed the invocation of `matlab -nodesktop -sd $INSTALL_DIR -batch 'generateCore()'` from `MatNWBInstaller.install()`.  As a result, the only thing the `install()` method now does is call `download()` and then run `git clean -dxf` on the downloaded clone of the MatNWB repository.

* Should the call to `git clean -dxf` be kept?
* Should `git clean -dxf` be run every time the `download()` method is called?

**Comment by yarikoptic** [comment]
frankly -- I don't know if there are any side effects or why we even originally called that `git clean -dxf`... it was added by you in e5261efb3cb7f81c7b0ad637ad00bbce16420566 and before the `generateCore` . Do you recall the reason/need for it?  if not -- we could test on some passed/failing file and deduce why it was needed , or just keep as historical artifact - I guess it doesn't hurt and should not take long

**Comment by yarikoptic** [comment]
Frankly - I don't know without trying, and behavior might change. Might be safest to just leave cleaning in
