### ISSUE TITLE
Switch deployment on drogon to use dandidav + davfs2 instead of datalad-fuse

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets-healthstatus#76]
Follow up to results from

- #67

**Comment by jwodder** [comment]
@yarikoptic Should any of the code for working with datalad-fuse and/or benchmarking different mount types be kept after this?

**Comment by yarikoptic** [comment]
Let's keep for now... may be we would make datalad-fuse speedy or decide to benchmark more of setups
