### ISSUE TITLE
Add parallelization across dandisets 

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets-healthstatus#9]
As locking at fsspec/datalad-fuse level virtually causes serial processing within each dandiset, I think we should parallelize across dandisets, so that with locking per each dandiset at fsspec level we would still be parallel across them and have reasonablish run time overall.

**Comment by jwodder** [comment]
@yarikoptic How many Dandisets should be processed at once?

**Comment by jwodder** [comment]
@yarikoptic Ping.

**Comment by yarikoptic** [comment]
should be a CLI option. I don't know what would be the optimal -- may be we could scale to number of CPUs or above!  Default -- I don't care, could be `1` (no parallelization)
